services:
  bot:
    image: binartist/deploybot-backend
    container_name: bot
    logging:
      options:
        max-size: "5m"
        max-file: "3"
    ports:
      - 8080:8080
    env_file:
      - pk.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./projects:/var/opt/projects
    restart: on-failure

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27018:27017
    env_file:
      - pk.env
    volumes:
      - ./data:/data/db

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    env_file:
      - ./pk.env
    environment:
      - PUID=1000
      - PGID=1000
      - VALIDATION=http
    volumes:
      - ./config:/config
    ports:
      - 443:443
      - 80:80
    restart: on-failure

networks:
  default:
    name: deploybot-network